# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='Restaurant_Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
