# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantlocation_restaurant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='Restaurant_Category',
            field=models.CharField(max_length=50, validators=[restaurants.validators.validate_category]),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='Restaurant_Email',
            field=models.EmailField(max_length=254, validators=[restaurants.validators.validate_email]),
        ),
    ]
